import { ISettings } from "../types/other";

const settingsArray: ISettings[] = [
  {
    id: 0,
    name: "Wysokość",
    key: "height",
    select: false,
    type: "number",
    value: 2300,
    isActive: true,
  },
  {
    id: 1,
    name: "Szerokość",
    key: "width",
    select: false,
    type: "number",
    value: 1000,
    isActive: true,
  },
  {
    id: 2,
    name: "Układ",
    key: "layout",
    select: true,
    options: [
      { id: 1, value: "I", name: "Proste" },
      { id: 2, value: "L", name: "Układ L" },
      { id: 3, value: "U", name: "Układ U" },
    ],
    value: "I",
    isActive: true,
  },
  {
    id: 3,
    name: "Grubość Wangi",
    key: "stringerThickness",
    select: false,
    type: "number",
    value: 80,
    isActive: true,
  },
  {
    id: 4,
    name: "Grubość Stopnia",
    key: "stepThickness",
    select: false,
    type: "number",
    value: 40,
    isActive: true,
  },
  {
    id: 5,
    name: "Podstopnice",
    key: "risers",
    select: true,
    options: [
      { id: 1, value: "true", name: "Tak" },
      { id: 2, value: "false", name: "Nie" },
    ],
    value: "false",
    isActive: true,
  },
  {
    id: 6,
    name: "Grubość Podstopnicy",
    key: "riserThickness",
    select: false,
    type: "number",
    value: 20,
    isActive: true,
    dependsOn: { key: "risers", value: "true" },
  },
  {
    id: 7,
    name: "Szerokość Stopnia",
    key: "stepWidth",
    select: false,
    type: "number",
    value: 295,
    isActive: true,
  },
  {
    id: 8,
    name: "Rodzaj Wangi",
    key: "stringerType",
    select: true,
    options: [
      { id: 1, value: "under", name: "Pod stopień" },
      { id: 2, value: "letIn", name: "Do stopnia" },
    ],
    value: "under",
    isActive: true,
  },
  {
    id: 9,
    name: "Zachodzenie Stopnia",
    key: "stepOverlapping",
    select: false,
    type: "number",
    value: 20,
    isActive: true,
  },
  {
    id: 10,
    name: "Wystawienie Stopnia",
    key: "stepIssuance",
    select: false,
    type: "number",
    value: 80,
    isActive: true,
    dependsOn: { key: "stringerType", value: "under" },
  },
  {
    id: 11,
    name: "Zagłęgienie Stopienia",
    key: "stepDeep",
    select: false,
    type: "number",
    value: 15,
    isActive: true,
    dependsOn: { key: "stringerType", value: "letIn" },
  },
  {
    id: 12,
    name: "Ostatni Stopień",
    key: "stepLast",
    select: true,
    options: [
      { id: 1, value: "true", name: "Tak" },
      { id: 2, value: "false", name: "Nie" },
    ],
    value: "true",
    isActive: true,
  },
];

export default settingsArray;
